### ISSUE TITLE
DataRecognitionClient/SpeechClient cannot handle subsequent recognitions

### ISSUE THREAD

**Issue by Plasma** [Azure-Samples/Cognitive-Speech-STT-Windows#24]
Hi,

I'm having trouble trying to use DataRecognitionClient processing anything more than one audio request in an app session. It can work, but you seem to need to wait a few moments for it to be "ready" for the next streaming attempt.

For example:

```csharp
// Create Client
var client = SpeechRecognitionServiceFactory.CreateDataClient(SpeechRecognitionMode.LongDictation, "en-US", "KEY");

// Prepare callback
client.OnResponseReceived += (sender, args) => ...; // Capture transcript here

// Send audio
client.SendAudio(...);

// No further processing
client.EndAudio();
```

If I attempt to run this code multiple times, even with a new client instance, the second instance will wait for a while/block/cause a crash.

I notice the SpeechClient.dll uses background threads, unsafe callbacks, etc, perhaps there is a race/threading issue.

**Comment by Plasma** [comment]
I think this is related to #23 #17 #20

**Comment by xin9le** [comment]
@priyaravi20 says
> Bing speech does not support multiple audios at the same time.
https://github.com/Azure-Samples/Cognitive-Speech-STT-Windows/issues/23#issuecomment-298711592

However, we really want to use Bing Speech API on multiple audios at the same time (= multi-thread). Because API key which API like Bing Speech has can't be embedded into client app for security reasons, we should use Bing Speech API on server side. Since the client application calls the server side API at an arbitrary timing, as a result we have to call Bing Speech API on multi-times at the same time.

Currently Bing Speech .NET SDK doesn't support it, our workaround is following.

- Ensure that multiple calls aren't made at the same time by queuing server side API calls.
- By separating calls of the Bing Speech API into separate processes, it makes pseudo multi-threading.

However, these approaches are NOT good because they degrade API response. That's the reason why, we want you to support multiple calls at the same time. Of course Google Cloud Speech API allows it.

Best regards,

**Comment by Plasma** [comment]
> However, we really want to use Bing Speech API on multiple audios at the same time (= multi-thread). 
I find its also not working consistently if you do it sequentially (one after the other), you need to wait an arbitrary delay before trying again. It's doing something super weird with background threads and unmanaged code.

**Comment by priyaravi20** [comment]
Have you tried the https://github.com/Azure-Samples/Cognitive-Speech-STT-ServiceLibrary which is library for calling the speech service from your service.

**Comment by priyaravi20** [comment]
Closing as per previous comment.
