### ISSUE TITLE
Need urgent help with intents.

### ISSUE THREAD

**Issue by KiransHub** [Azure-Samples/Cognitive-Speech-STT-Windows#29]
Hi guys, 

I seem to having a problem with CreateMicrophoneClientWithIntent. I get microphone recognitions but intents don't seem to get returned. I'm actually attending a hackathon event hosted by Microsoft and I don't seem to be getting the answers I need. 

Where do I get my LUIS Subscription ID for use with your solution? Where can I find my APP Id? 

I've currently been using https://www.luis.ai to obtain these keys. **I have tried using the API key for the luisSubscriptionId variable and the app ID for the luisAppId variable** but the intent handler never gets called. 

Sorry to label this as urgent but ,I'm actually attending a hackathon where I intend to implement this so time is somewhat limited.

**Comment by KiransHub** [comment]
Do I need to specify the Authentication Uri? What should it be?

**Comment by KiransHub** [comment]
I keep getting: 
--- Error received by OnConversationErrorHandler() ---
Error code: InternalError
Error text: Transport error

**Comment by priyaravi20** [comment]
Please reach out on LUIS forums if you are facing auth errors with LUIS keys.

**Comment by michaelz-voice2sports** [comment]
I am having the exact same issue and have searched the LUIS forums extensively for weeks! How can I communicate with KiransHub to work together and/or find the appropriate LUIS forums topic and answer? Please help. All other attempts at resolving this have been futile. Thank you. 

michaelz@voice2sports.com

**Comment by cahann** [comment]
Which API are you calling? Are you using the SDK or calling the API directly?

**Comment by michaelz-voice2sports** [comment]
Both. The API calls directly work. However the SDK example does not.

Thanks,

Michael

On Sep 13, 2017, at 8:19 AM, Carol Hanna <notifications@github.com<mailto:notifications@github.com>> wrote:


Which API are you calling? Are you using the SDK or calling the API directly?

**Comment by raaaar** [comment]
Just tried the example, worked for me. The only time I observed the same exceptions was when I forgot to paste my cognitive services subscription key in the top right edit box. Apart from that, it could be an outdated version of the Microsoft.ProjectOxford.SpeechRecognition nuget (< 1.0.0.6).

**Comment by raaaar** [comment]
Never mind. Found the issue, SDK is built against an old LUIS API version, and apparently requests hitting the old endpoint are not always properly rerouted. We're looking to make the LUIS endpoint a configurable parameter.

**Comment by michaelz-voice2sports** [comment]
Thanks. I'm actually running it in Xcode 8.2.1,  not Visual Studio 2017 (Mac or Win) or Xamarin so no nuget packages. What was your VS and nuget configuration that worked? Might be worth a try on my side. (The sample docs for iOS example only mention using the STT-iOS with Xcode so that's what I've followed). Could it be that your are testing directly on Windows and/or Windows Phone emulated/physical?

[Now that I think about it, since I posted this under STT-Windows, I might have already tested on at least VS2017 for Mac and nuget, or even VS2015/17 on Win 8 or 10 and nuget but I've either got TME syndrome or a case of CRS. (TME stands for "Too Many Environments"... I can't remember what CRS is or even what it does to you, but every one I talk to tells me I have it).  So I'll revisit, but the issue definitely remains for me for all things iOS.]

Thanks,

Michael

On Sep 14, 2017, at 9:32 AM, raaaar <notifications@github.com<mailto:notifications@github.com>> wrote:


Just tried the example, worked for me. The only time I observed the same exceptions was when I forgot to paste my cognitive services subscription key in the top right edit box. Apart from that, it could be an outdated version of the Microsoft.ProjectOxford.SpeechRecognition nuget (< 1.0.0.6).

**Comment by raaaar** [comment]
I tried with VS 2015, speech client nuget 1.0.0.6 and a brand new LUIS account with an app hosted by westus.api.cognitive.microsoft.com. I don't think this could be platform related (the code that talks to LUIS is cross-platform), anyways will try the iOS sample and let you know how it goes.
